server:
  port: 1010
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /sandbox-living

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sandbox-living

