server:
  port: 1010
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /sandbox-living
  error:
    whitelabel:
      enabled: false # 禁用默认错误页面

spring:
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false # 禁用默认的静态资源映射
  application:
    name: sandbox-living

netty:
  device:
    port: 9001
    boss-threads: 1
    worker-threads: 4
    path: /device/ws
    timeout: 60  # 设备超时时间较短
  user:
    port: 9002
    boss-threads: 2
    worker-threads: 8
    path: /user/ws
    timeout: 120 # 用户超时时间较长
